version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    networks:
      - symfony
    depends_on:
      - redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - symfony
    depends_on:
      - php

  redis:
    image: redis:alpine
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
